### ISSUE TITLE
Client-side routing and bookmarks

### ISSUE THREAD

**Issue by TrueWill** [brajevicm/next-universal-route#14]
Thanks for developing this!

I'm trying to replace Next.js's router with yours, as we're using [next export mode](https://nextjs.org/docs/advanced-features/static-html-export) and need advanced routing (client-side).

Using `Link` with `generateUrl` works great, and shows the proper page at the proper URL.

However if the user refreshes the page (or bookmarks it and comes back to it), they'll get a 404.

Is there a way to get initial routes to work (such as coming to the site from an external link) with client-side routing?

**Comment by brajevicm** [comment]
Hey, thanks for creating the issue. I personally haven't used `next export` yet, so I don't know what happens under the hood. I will get back to you once I get to play with it.

**Comment by TrueWill** [comment]
@brajevicm Thank you for the reply! Our team gave up on next export mode - it's clear that the Next.js authors do _not_ want people to replace their router, and that the framework is not full-featured unless you run a server (not surprising considering Vercel's business model). We gave in and stopped using next export.
