### ISSUE TITLE
Typescript error when using Link component

### ISSUE THREAD

**Issue by godness84** [brajevicm/next-universal-route#3]
Using the Link component as described in the docs:
```typescript
<Link href={IndexRoute.generateUrl()}>
  <a>Index</a>
</Link>
```

Typescript complains with `Type 'Element' is missing the following properties from type 'ReactChildren': map, forEach, count, only, toArray. The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & LinkProps'`

I suppose it comes from the TS definition of `children` field of `Link` component: it is typed as `ReactChildren` but maybe it should be `ReactNode`.

**Comment by brajevicm** [comment]
@godness84 
Thanks for checking this out. 
It should be fixed now.
